# Generated by Django 6.0.2 on 2026-03-13 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id_emprestimos', models.AutoField(db_column='ID_Emprestimos', primary_key=True, serialize=False)),
                ('nome_requerente', models.CharField(blank=True, db_column='Nome_Requerente', max_length=200, null=True)),
                ('matricula', models.CharField(blank=True, db_column='Matricula', max_length=100, null=True)),
                ('data_retirada', models.DateField(db_column='Data_Retirada')),
                ('data_entrega', models.DateField(db_column='Data_Entrega')),
            ],
            options={
                'db_table': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Laboratorios',
            fields=[
                ('id_laboratorios', models.AutoField(db_column='ID_Laboratorios', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=150, null=True)),
                ('localizacao', models.CharField(blank=True, db_column='Localizacao', max_length=150, null=True)),
                ('area', models.DecimalField(blank=True, db_column='Area', decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Laboratorios',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(db_column='ID_Material', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=150, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=150, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=100, null=True)),
                ('fabricante', models.CharField(blank=True, db_column='Fabricante', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Permissoes',
            fields=[
                ('id_permissoes', models.AutoField(db_column='ID_Permissoes', primary_key=True, serialize=False)),
                ('permissao', models.CharField(db_column='Permissao', max_length=150)),
            ],
            options={
                'db_table': 'Permissoes',
            },
        ),
        migrations.CreateModel(
            name='EmprestimoExterno',
            fields=[
                ('id_emprestimo', models.OneToOneField(db_column='ID_Emprestimo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='principal.emprestimos')),
                ('atividade', models.TextField(blank=True, db_column='Atividade', null=True)),
                ('associacao', models.TextField(blank=True, db_column='Associacao', null=True)),
            ],
            options={
                'db_table': 'Emprestimo_Externo',
            },
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id_agendamentos', models.AutoField(db_column='ID_Agendamentos', primary_key=True, serialize=False)),
                ('tipo_de_atividade', models.TextField(blank=True, db_column='Tipo_de_Atividade', null=True)),
                ('data_inicial', models.DateField(blank=True, db_column='Data_Inicial', null=True)),
                ('data_final', models.DateField(blank=True, db_column='Data_Final', null=True)),
                ('horario_inicio', models.TimeField(blank=True, db_column='Horario_Inicio', null=True)),
                ('horario_final', models.TimeField(blank=True, db_column='Horario_Final', null=True)),
                ('id_laboratorio', models.ForeignKey(db_column='ID_Laboratorio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.laboratorios')),
            ],
            options={
                'db_table': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumiveis',
            fields=[
                ('id_material', models.OneToOneField(db_column='ID_Material', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='principal.material')),
            ],
            options={
                'db_table': 'Material_Consumiveis',
            },
        ),
        migrations.CreateModel(
            name='MaterialEquipamentos',
            fields=[
                ('id_material', models.OneToOneField(db_column='ID_Material', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='principal.material')),
                ('patrimonio', models.CharField(blank=True, db_column='Patrimonio', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Material_Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='MaterialReagentes',
            fields=[
                ('id_material', models.OneToOneField(db_column='ID_Material', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='principal.material')),
                ('lote', models.CharField(blank=True, db_column='Lote', max_length=100, null=True)),
                ('validade', models.CharField(db_column='Validade', max_length=100)),
                ('medida', models.CharField(blank=True, db_column='Medida', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Material_Reagentes',
            },
        ),
        migrations.CreateModel(
            name='MaterialVidrarias',
            fields=[
                ('id_material', models.OneToOneField(db_column='ID_Material', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='principal.material')),
            ],
            options={
                'db_table': 'Material_Vidrarias',
            },
        ),
        migrations.CreateModel(
            name='MateriaisAgendamentos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_agendamentos', 'id_materiais', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_agendamentos', models.ForeignKey(db_column='ID_Agendamentos', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.agendamentos')),
                ('id_materiais', models.ForeignKey(db_column='ID_Materiais', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.material')),
            ],
            options={
                'db_table': 'Materiais_Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='EstoqueLaboratorio',
            fields=[
                ('id_estoque', models.AutoField(db_column='ID_Estoque', primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('id_laboratorio', models.ForeignKey(db_column='ID_Laboratorio', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.laboratorios')),
                ('id_material', models.ForeignKey(db_column='ID_Material', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.material')),
            ],
            options={
                'db_table': 'Estoque_Laboratorio',
            },
        ),
        migrations.CreateModel(
            name='EmprestimosMateriais',
            fields=[
                ('pk', models.CompositePrimaryKey('id_material', 'id_emprestimos', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id_emprestimos', models.ForeignKey(db_column='ID_Emprestimos', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.emprestimos')),
                ('id_material', models.ForeignKey(db_column='ID_Material', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.material')),
            ],
            options={
                'db_table': 'Emprestimos_Materiais',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(db_column='ID_Usuarios', primary_key=True, serialize=False)),
                ('nome', models.CharField(db_column='Nome', max_length=200)),
                ('email', models.CharField(db_column='Email', max_length=200, unique=True)),
                ('senha', models.CharField(db_column='Senha', max_length=100)),
                ('criado_em', models.DateTimeField(blank=True, db_column='Criado_em', null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, db_column='Atualizado_em', null=True)),
                ('id_permissoes', models.ForeignKey(blank=True, db_column='ID_Permissoes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.permissoes')),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='id_usuarios',
            field=models.ForeignKey(blank=True, db_column='ID_Usuarios', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuarios'),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='id_usuarios',
            field=models.ForeignKey(db_column='ID_Usuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='principal.usuarios'),
        ),
    ]
