# Generated by Django 6.0.2 on 2026-03-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='descricao_atividade',
            field=models.TextField(blank=True, db_column='Descricao_Atividade', null=True),
        ),
    ]
